#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

unshift @{app->static->paths} => 'client';

get '/' => sub {
  my $c = shift;
  $c->reply->static('index.html');
};

app->start;
