#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

unshift @{app->static->paths} => 'client';

get '/' => sub {
  my $c = shift;
  $c->reply->static('index.html');
};

# Multipart upload handler
post '/upload' => sub {
  my $c     = shift;
  my $image = $c->param('image');
  my $size  = $image->size;
  my $name  = $image->filename;
  $c->render(text => "Thanks for uploading $size byte file $name.");
};

app->start;
